import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import "./RoomsOfLight.css";

const frames=[
  {a:.12,b:.25,body:<><h1>ARRIVAL</h1><blockquote>“Every beginning contains more possibility than certainty.”</blockquote><p className="arrival-room-label">Room 01 · 2026</p></>},
  {a:.36,b:.55,body:<><h2>Arrival is the first room.</h2><p>It is also the work in which the idea of a room is still at its most recognisable. Surfaces meet, light enters from somewhere beyond the frame, and the composition retains enough architectural logic for us to imagine stepping inside it.</p><p>But the space was never intended to be built.</p><p>Its purpose is not to describe architecture, but to create the sensation that precedes understanding: entering somewhere for the first time and not yet knowing what it might become.</p></>},
  {a:.66,b:.85,body:<><h2>Before certainty</h2><p>Arrival is constructed around anticipation.</p><p>The warm light suggests a destination without revealing one. The darker surfaces provide weight, but not enclosure. Nothing in the composition demands attention individually; the tension comes from the relationship between what is visible and what remains outside the image.</p><p>The room feels complete enough to enter and unfinished enough to imagine.</p><p>That ambiguity became the starting point for the entire exhibition.</p></>}
];
function opacity(p:number,a:number,b:number){const edge=Math.min(.028,(b-a)/4);return Math.max(0,Math.min(1,(p-a)/edge,(b-p)/edge));}
export default function ArrivalRoom(){const ref=useRef<HTMLElement>(null);const [progress,setProgress]=useState(0);useEffect(()=>{let raf=0;const update=()=>{if(!ref.current)return;const r=ref.current.getBoundingClientRect();setProgress(Math.max(0,Math.min(1,-r.top/(r.height-window.innerHeight))));};const onScroll=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(update)};update();addEventListener("scroll",onScroll,{passive:true});addEventListener("resize",onScroll);return()=>{removeEventListener("scroll",onScroll);removeEventListener("resize",onScroll);cancelAnimationFrame(raf)}} ,[]);
return <article className="arrival-page"><nav className="arrival-nav"><span>Rooms of Light / 01</span><Link to="/projects/digital-art-gallery/rooms-of-light">Back to exhibition</Link></nav><section ref={ref} className="arrival-scroll"><div className="arrival-stage"><div className="arrival-canvas"><img src="/assets/rooms-of-light/arrival.png" alt="Arrival"/><div className="arrival-overlays">{frames.map((f,i)=><div key={i} className={`arrival-fragment arrival-fragment--${i+1}`} style={{opacity:opacity(progress,f.a,f.b),transform:`translateY(${(1-opacity(progress,f.a,f.b))*6}px)`}}>{f.body}</div>)}</div></div></div></section><nav className="arrival-exit"><Link to="/projects/digital-art-gallery/rooms-of-light">← Rooms of Light</Link><Link to="/projects/digital-art-gallery/rooms-of-light#open-sky">Next room<br/>Open Sky →</Link></nav></article>}
