import { Link } from "react-router-dom";
import "./RoomsOfLight.css";

const base = "/assets/rooms-of-light/";
type WorkProps = { n:string; title:string; image:string; className?:string; id?:string; arrival?:boolean };
function Work({n,title,image,className="",id,arrival}:WorkProps){
  const content = <><div className="rol-image"><img src={`${base}${image}`} alt={`${title}, from Rooms of Light`} /></div><div className="rol-work-meta"><span>{n}</span><h3>{title}</h3></div></>;
  return arrival ? <Link id={id} className={`rol-work ${className}`} to="/projects/digital-art-gallery/rooms-of-light/arrival">{content}</Link> : <article id={id} className={`rol-work ${className}`}>{content}</article>;
}

export default function RoomsOfLight(){return <article className="rol-page">
  <section className="rol-hero"><p className="rol-kicker">Digital Art Gallery · Exhibition 01 · 2026</p><h1><span>Rooms</span><span>of Light</span></h1><div className="rol-hero-copy"><p>Eight studies on light, space and the quiet transformations between them.</p><p>Across eight works, imagined rooms gradually move away from architecture and towards something less certain — spaces somewhere between memory, abstraction and possibility.</p></div><span className="rol-threshold" aria-hidden="true" /></section>
  <section className="rol-intro"><div><p className="rol-kicker">The exhibition</p><h2>Not a collection.<br/>A sequence.</h2></div><p>Rooms of Light begins with a simple idea: that light does more than reveal a space. It changes its weight. Its distance. Its temperature. Sometimes, even its meaning.<br/><br/>The first rooms are discovered. Then they begin to change. Eventually, the room itself becomes less important than what remains after it.</p></section>
  <section className="rol-movement rol-movement--one"><header><p>Movement I</p><h2>Discovering space</h2><span>01–03</span></header><div className="rol-movement-copy"><p className="rol-lead">A room appears.</p><p className="rol-description">Walls, openings, distances and directions remain readable. Light enters spaces that still feel possible to understand — but with every work, that certainty becomes slightly less important.</p></div><div className="rol-grid rol-grid--one"><Work arrival n="01" title="Arrival" image="arrival.png" className="rol-arrival"/><Work id="open-sky" n="02" title="Open Sky" image="open-sky.png"/><Work n="03" title="Signals" image="signals.png" className="rol-wide"/></div></section>
  <section className="rol-transition rol-transition--warm"><p>The room is still there.<br/>But it no longer needs to behave like one.</p></section>
  <section className="rol-movement rol-movement--two"><header><p>Movement II</p><h2>Transforming space</h2><span>04–06</span></header><div className="rol-movement-copy rol-movement-copy--split"><p className="rol-lead">The boundaries begin to soften.</p><p className="rol-description">Architecture gives way to relationships between surfaces, forms, colour and light. The room becomes a material rather than a setting.</p></div><div className="rol-grid rol-grid--two"><Work n="04" title="Between Shapes" image="between-shapes.png"/><Work n="05" title="Bloom" image="bloom.png" className="rol-bloom"/><Work n="06" title="Blue Hour" image="blue-hour.png" className="rol-wide rol-blue"/></div></section>
  <section className="rol-transition rol-transition--cool"><p>Less structure.<br/>Less certainty.<br/>More space.</p></section>
  <section className="rol-movement rol-movement--three"><header><p>Movement III</p><h2>Leaving space</h2><span>07–08</span></header><div className="rol-movement-copy rol-movement-copy--quiet"><p className="rol-lead">What remains when almost everything else disappears?</p><p className="rol-description">Edges soften. Objects recede. The distinction between room, surface and atmosphere becomes increasingly uncertain.</p></div><div className="rol-grid rol-grid--three"><Work n="07" title="Still Water" image="still-water.png"/><Work n="08" title="North" image="north.png" className="rol-north"/></div></section>
  <section className="rol-ending"><p className="rol-kicker">An open ending</p><h2>Rooms of Light ends where it began: with possibility.</h2><div><p>The first work enters a space.<br/>The last one looks beyond it.</p><p>Everything between them is an attempt to understand what light can change.</p><p>The journey does not arrive at an answer.<br/><span>It opens.</span></p></div></section>
  <section id="digital-edition" className="rol-edition"><h2>The exhibition does not have to end here.</h2><div><p>Each work has also been carefully adapted for the screens where ideas happen.</p><a href="#digital-edition">View the Digital Edition →</a></div></section>
</article>}
